name: retail_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  bloc: ^8.1.3
  collection: ^1.18.0
  english_words: ^4.0.0
  flutter:
    sdk: flutter
  http: ^1.2.1
  json_annotation: ^4.8.1
  mockito: ^5.4.4
  provider: ^6.0.0
  rxdart: ^0.27.7

dev_dependencies:
  bloc_test: ^9.0.0
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
